// Code generated by github.com/scottshotgg/configsquared; DO NOT EDIT.

// It is in your best interest NOT to edit this file as it will be removed if re-generated.

// TODO: might be able to improve this later

package config

type anyFlag struct {
	set   bool
	value string
}

// If flag is not provided it will not get to this function
func (a *anyFlag) Set(x string) error {
	// Ultimately, every flag argument that comes in is a string. Putting the value into an interface
	// would just add one more wrapper around whatever value is already stringified.
	// Thus, an `any` is really just a `string`
	// Any is really not here for any reason; I, personally, would never use it and don't see a point.
	// However, it may be of value to someone if they just want to accept anything, although that could
	// be done with a string value.
	a.value = x

	a.set = true

	return nil
}

func (a *anyFlag) String() string {
	return a.value
}
