// Code generated by github.com/scottshotgg/configsquared; DO NOT EDIT.

// It is in your best interest NOT to edit this file as it will be removed if re-generated.

// TODO: templatize 32 and 64 bit

package config

import (
	"strconv"
)

type float64Flag struct {
	set    bool
	value  float64
	sValue string
}

// If flag is not provided it will not get to this function
func (f *float64Flag) Set(x string) error {
	// Set the string value
	f.sValue = x

	// Parse the value from the provided string
	var value, err = strconv.ParseFloat(f.sValue, 64)
	if err != nil {
		// TODO: test this out
		return err
	}

	// Set the actual value
	f.value = value

	// Mark the flag as set
	f.set = true

	return nil
}

func (f *float64Flag) String() string {
	return f.sValue
}
