// Code generated by github.com/scottshotgg/configsquared; DO NOT EDIT.

// It is in your best interest NOT to edit this file as it will be removed if re-generated.

package config

// TODO: make stringer
// implement JSON un/marshaling

type MongoConfig struct {
	address string
}

func (c *MongoConfig) Address() string {
	return c.address
}
