// Code generated by github.com/scottshotgg/configsquared; DO NOT EDIT.

// It is in your best interest NOT to edit this file as it will be removed if re-generated.

package config

import (
	"errors"
)

type runeFlag struct {
	set    bool
	value  rune
	sValue string
}

// TODO: flesh this out more

// If flag is not provided it will not get to this function
func (r *runeFlag) Set(x string) error {
	var rs = []rune(x)

	if len(rs) > 1 {
		return errors.New("rune flag only accepts one rune")
	}

	r.value = rs[0]

	r.set = true

	return nil
}

func (r *runeFlag) String() string {
	return r.sValue
}
