// Code generated by github.com/scottshotgg/configsquared; DO NOT EDIT.

// It is in your best interest NOT to edit this file as it will be removed if re-generated.

package config

import (
	"fmt"
	"strings"
)

type stringArrayFlag struct {
	set    bool
	sValue string
	value  []string
}

// If flag is not provided it will not get to this function
func (sf *stringArrayFlag) Set(x string) error {
	sf.sValue = x

	sf.set = true

	fmt.Println("value of string array:", x)

	sf.value = strings.Split(x, ",")
	if len(sf.value) == 0 && len(x) != 0 {
		// TODO: remove panic
		panic(fmt.Sprintf("not able to parse given argument to string slice: %+v", x))
	}

	fmt.Println("after split:", sf.value)

	return nil
}

func (sf *stringArrayFlag) String() string {
	return sf.sValue
}
