// Code generated by github.com/scottshotgg/configsquared; DO NOT EDIT.

// It is in your best interest NOT to edit this file as it will be removed if re-generated.

package config

import (
	"strconv"
)

type uint32Flag struct {
	set    bool
	value  uint32
	sValue string
}

// If flag is not provided it will not get to this function
func (u *uint32Flag) Set(x string) error {
	// Set the string value
	u.sValue = x

	// Parse the value from the provided string
	var value, err = strconv.ParseUint(u.sValue, 10, 32)
	if err != nil {
		// TODO: test this out
		return err
	}

	// Set the actual value
	u.value = uint32(value)

	// Mark the flag as set
	u.set = true

	return nil
}

func (u *uint32Flag) String() string {
	return u.sValue
}
