// Code generated by github.com/scottshotgg/configsquared; DO NOT EDIT.

// It is in your best interest NOT to edit this file as it will be removed if re-generated.

package config

import (
	"strconv"
	"time"
)

type unixFlag struct {
	set    bool
	value  time.Time
	sValue string
}

// If flag is not provided it will not get to this function
func (u *unixFlag) Set(x string) error {
	// Set the string value
	u.sValue = x

	// Parse the value from the provided string
	var value, err = strconv.ParseInt(u.sValue, 10, 64)
	if err != nil {
		// TODO: test this out
		return err
	}

	// Set the actual value
	u.value = time.Unix(value, 0)

	// Mark the flag as set
	u.set = true

	return nil
}

func (u *unixFlag) String() string {
	return u.sValue
}
