// Code generated by github.com/scottshotgg/configsquared; DO NOT EDIT.

// It is in your best interest NOT to edit this file as it will be removed if re-generated.

package config

import (
	"fmt"
	"net/url"
	"strings"
)

type urlArrayFlag struct {
	set    bool
	value  []url.URL
	sValue string
}

// If flag is not provided it will not get to this function
func (u *urlArrayFlag) Set(x string) error {
	// Set the string value
	u.sValue = x

	// Mark the flag as set
	u.set = true

	var urls = strings.Split(x, ",")
	if len(u.value) == 0 && len(x) != 0 {
		// TODO: remove panic
		panic(fmt.Sprintf("not able to parse given argument to url slice: %+v", x))
	}

	for _, urll := range urls {
		// Parse the value from the provided string
		var value, err = url.ParseRequestURI(urll)
		if err != nil {
			// TODO: test this out
			return err
		}

		// Set the actual value
		u.value = append(u.value, *value)
	}

	return nil
}

func (u *urlArrayFlag) String() string {
	return u.sValue
}
