// Code generated by github.com/scottshotgg/configsquared; DO NOT EDIT.

// It is in your best interest NOT to edit this file as it will be removed if re-generated.

package config

import "strconv"

// TODO: Might just be able to do bools with a flag and have them

type boolFlag struct {
	set    bool
	value  bool
	sValue string
}

// If flag is not provided it will not get to this function
func (sf *boolFlag) Set(x string) error {
	// Set the string value
	sf.sValue = x

	// Parse the value from the provided string
	var value, err = strconv.ParseBool(sf.sValue)
	if err != nil {
		// TODO: test this out
		return err
	}

	// Set the actual value
	sf.value = value

	// Mark the flag as set
	sf.set = true

	return nil
}

func (sf *boolFlag) String() string {
	return sf.sValue
}
