// Code generated by github.com/scottshotgg/configsquared; DO NOT EDIT.

// It is in your best interest NOT to edit this file as it will be removed if re-generated.

package config

import (
	"flag"
)

type Config struct {
	port  string
	ports []string
}

var (
	// Internal singleton config to avoid re-parse if called multiple times
	c Config
)

func (c *Config) Port() string {
	return c.port
}
func (c *Config) Ports() []string {
	return c.ports
}

func Parse() *Config {
	if !flag.Parsed() {
		var f = newFlags()

		flag.Parse()

		f.required()
		f.defaults()

		c = f.toConfig()
	}

	return &c
}
