// Code generated by github.com/scottshotgg/configsquared; DO NOT EDIT.

// It is in your best interest NOT to edit this file as it will be removed if re-generated.

package config

import "flag"

type flags struct {
	at      unixFlag
	remote  urlFlag
	uint64  uint64Flag
	rune    runeFlag
	retries intFlag
	when    timeFlag
	idc     anyFlag
	int64   int64Flag
	byte    byteFlag
	port    stringFlag
	timeout durationFlag
	int32   int32Flag
	uint32  uint32Flag
	mock    boolFlag
}

func newFlags() *flags {
	var f flags

	flag.Var(&f.at, "at", "")
	flag.Var(&f.remote, "remote", "")
	flag.Var(&f.uint64, "uint64", "")
	flag.Var(&f.rune, "rune", "")
	flag.Var(&f.retries, "retries", "Set the default HTTP timeout")
	flag.Var(&f.when, "when", "")
	flag.Var(&f.idc, "idc", "")
	flag.Var(&f.int64, "int64", "")
	flag.Var(&f.byte, "byte", "")
	flag.Var(&f.port, "port", "Port that the server is hosted on")
	flag.Var(&f.timeout, "timeout", "")
	flag.Var(&f.int32, "int32", "")
	flag.Var(&f.uint32, "uint32", "")
	flag.Var(&f.mock, "mock", "Whether to mock the backing data storage for testing")

	// nested struct fields

	f.when.layout = "2006-01-02T15:04:05Z07:00"

	return &f
}

func (f *flags) required() {
	if !f.port.set {
		// just for now
		panic("port is a required flag")
	}
}

func (f *flags) defaults() {
	if !f.retries.set {
		var err = f.retries.Set("5")
		if err != nil {
			// _probably_ just for now
			panic(err)
		}
	}
}

func (f *flags) toConfig() Config {
	return Config{
		at:      f.at.value,
		remote:  f.remote.value,
		uint64:  f.uint64.value,
		rune:    f.rune.value,
		retries: f.retries.value,
		when:    f.when.value,
		idc:     f.idc.value,
		int64:   f.int64.value,
		byte:    f.byte.value,
		port:    f.port.value,
		timeout: f.timeout.value,
		int32:   f.int32.value,
		uint32:  f.uint32.value,
		mock:    f.mock.value,
	}
}
