// Code generated by github.com/scottshotgg/configsquared; DO NOT EDIT.

// It is in your best interest NOT to edit this file as it will be removed if re-generated.

package config

import (
	"strconv"
)

type intFlag struct {
	set    bool
	value  int
	sValue string
}

// If flag is not provided it will not get to this function
func (sf *intFlag) Set(x string) error {
	// Set the string value
	sf.sValue = x

	// Parse the value from the provided string
	var value, err = strconv.ParseInt(sf.sValue, 10, 32)
	if err != nil {
		// TODO: test this out
		return err
	}

	// Set the actual value
	sf.value = int(value)

	// Mark the flag as set
	sf.set = true

	return nil
}

func (sf *intFlag) String() string {
	return sf.sValue
}
