// Code generated by github.com/scottshotgg/configsquared; DO NOT EDIT.

// It is in your best interest NOT to edit this file as it will be removed if re-generated.

package config

import "fmt"

type stringArrayFlag struct {
	set    bool
	sValue string
	value  []string
}

// If flag is not provided it will not get to this function
func (sf *stringArrayFlag) Set(x string) error {
	sf.sValue = x

	sf.set = true

	fmt.Println("value of string array:", x)

	sf.value = []string{}

	return nil
}

func (sf *stringArrayFlag) String() string {
	return sf.sValue
}
