// Code generated by github.com/scottshotgg/configsquared; DO NOT EDIT.

// It is in your best interest NOT to edit this file as it will be removed if re-generated.

package config

import (
	"time"
)

// TODO: will need a format specifier
// this will have to be templated for a format
type timeFlag struct {
	set    bool
	value  time.Time
	layout string
	sValue string
}

// If flag is not provided it will not get to this function
func (t *timeFlag) Set(x string) error {
	// Set the string value
	t.sValue = x

	// Parse the value from the provided string
	var value, err = time.Parse(t.layout, x)
	if err != nil {
		return err
	}

	// Set the actual value
	t.value = value

	// Mark the flag as set
	t.set = true

	return nil
}

func (t *timeFlag) String() string {
	return t.sValue
}
