// Code generated by github.com/scottshotgg/configsquared; DO NOT EDIT.

// It is in your best interest NOT to edit this file as it will be removed if re-generated.

package config

import "flag"

type flags struct {
	port stringFlag
	// TODO: need to do something here to disambiguate this flag from something actually named that
	dbPort stringFlag
	dbAddr stringFlag
}

func newFlags() *flags {
	var f flags

	flag.Var(&f.port, "port", "")
	flag.Var(&f.dbPort, "db.port", "")
	flag.Var(&f.dbAddr, "db.addr", "")

	// nested struct fields

	return &f
}

func (f *flags) required() {

}

func (f *flags) defaults() {

}

func (f *flags) toConfig() Config {
	return Config{
		port: f.port.value,
		db: Db{
			port: f.dbPort.value,
			addr: f.dbAddr.value,
		},
	}
}
