// Code generated by github.com/scottshotgg/configsquared; DO NOT EDIT.

// It is in your best interest NOT to edit this file as it will be removed if re-generated.

package config

import (
	"flag"
)

type Config struct {
	// %configFields%
}

var (
	// Internal singleton config to avoid re-parse if called multiple times
	c Config
)

// %configGetters%

func Parse() *Config {
	if !flag.Parsed() {
		var f = newFlags()

		flag.Parse()

		f.required()
		f.defaults()

		c = f.toConfig()
	}

	return &c
}
