// Code generated by github.com/scottshotgg/configsquared; DO NOT EDIT.

// It is in your best interest NOT to edit this file as it will be removed if re-generated.

package config

type flags struct {
	// flagFields
}

func newFlags() *flags {
	var f flags

	// flagVars

	// nested struct fields

	// extraFields

	return &f
}

func (f *flags) required() {
	// requiredIfs
}

func (f *flags) defaults() {
	// defaultIfs
}

func (f *flags) toConfig() Config {
	return Config{
		// mappers
	}
}
