// Code generated by github.com/scottshotgg/configsquared; DO NOT EDIT.

// It is in your best interest NOT to edit this file as it will be removed if re-generated.

package config

import (
	"errors"
)

// TODO: this file will need to be templatized for whatever type of array they want

type arrayFlag struct {
	set bool
	// value  []
	sValue string
}

// If flag is not provided it will not get to this function
func (a *arrayFlag) Set(x string) error {
	// TODO: implement this
	return errors.New("type not implemented; array")

	// // Set the string value
	// sf.sValue = x

	// // Parse the value from the provided string
	// var value, err = strconv.ParseBool(sf.sValue)
	// if err != nil {
	// 	// TODO: test this out
	// 	return err
	// }

	// // Set the actual value
	// sf.value = value

	// // Mark the flag as set
	// sf.set = true

	// return nil
}

func (a *arrayFlag) String() string {
	return a.sValue
}
