// Code generated by github.com/scottshotgg/configsquared; DO NOT EDIT.

// It is in your best interest NOT to edit this file as it will be removed if re-generated.

package config

import (
	"time"
)

type durationFlag struct {
	set    bool
	value  time.Duration
	sValue string
}

// If flag is not provided it will not get to this function
func (d *durationFlag) Set(x string) error {
	// In this case 'x' should be something like "2m" or "5h", etc

	// Parse the value from the provided string
	var value, err = time.ParseDuration(x)
	if err != nil {
		return err
	}

	// Set the string value
	d.sValue = x

	// Set the actual value
	d.value = value

	// Mark the flag as set
	d.set = true

	return nil
}

func (d *durationFlag) String() string {
	return d.sValue
}
