// Code generated by github.com/scottshotgg/configsquared; DO NOT EDIT.

// It is in your best interest NOT to edit this file as it will be removed if re-generated.

package config

import (
	"errors"
	"net/url"
)

type urlFlag struct {
	set    bool
	value  url.URL
	sValue string
}

// If flag is not provided it will not get to this function
func (u *urlFlag) Set(x string) error {
	// TODO: implement this
	return errors.New("type not implemented; url")

	// // Set the string value
	// u.sValue = x

	// // Parse the value from the provided string
	// var value, err = strconv.Parseurl(u.sValue, 10, 0)
	// if err != nil {
	// 	// TODO: test this out
	// 	return err
	// }

	// // Set the actual value
	// u.value = url(value)

	// // Mark the flag as set
	// u.set = true

	// return nil
}

func (u *urlFlag) String() string {
	return u.sValue
}
